import { Users } from "../../types";

export const USERS: Users = [
  {
    id: 1,
    name: "John Doe",
    email: "john.doe@example.com",
    gender: "male",
    isVerified: true,
    dateOfBirth: "1985-07-12",
  },
  {
    id: 2,
    name: "Jane Smith",
    email: "jane.smith@example.com",
    gender: "female",
    isVerified: true,
    dateOfBirth: "1990-04-25",
  },
  {
    id: 3,
    name: "Michael Johnson",
    email: "michael.johnson@example.com",
    gender: "male",
    isVerified: false,
    dateOfBirth: "1993-11-18",
  },
  {
    id: 4,
    name: "Emily Davis",
    email: "emily.davis@example.com",
    gender: "female",
    isVerified: true,
    dateOfBirth: "1988-09-03",
  },
  {
    id: 5,
    name: "David Wilson",
    email: "david.wilson@example.com",
    gender: "male",
    isVerified: true,
    dateOfBirth: "1995-02-08",
  },
  {
    id: 6,
    name: "Sarah Brown",
    email: "sarah.brown@example.com",
    gender: "female",
    isVerified: false,
    dateOfBirth: "1992-06-14",
  },
  {
    id: 7,
    name: "James Lee",
    email: "james.lee@example.com",
    gender: "male",
    isVerified: true,
    dateOfBirth: "1987-03-29",
  },
  {
    id: 8,
    name: "Olivia Harris",
    email: "olivia.harris@example.com",
    gender: "female",
    isVerified: true,
    dateOfBirth: "1994-01-17",
  },
  {
    id: 9,
    name: "William Martin",
    email: "william.martin@example.com",
    gender: "male",
    isVerified: false,
    dateOfBirth: "1991-08-22",
  },
  {
    id: 10,
    name: "Ava Anderson",
    email: "ava.anderson@example.com",
    gender: "female",
    isVerified: true,
    dateOfBirth: "1989-12-07",
  },
];
