import { Products } from "../../types";

export const PRODUCTS: Products = [
  {
    id: 1,
    discount: 25,
    available: false,
    materials: ["Wood", "Canvas"],
    name: "Canvas Painting",
    price: 199.99,
  },
  {
    id: 2,
    discount: 5,
    available: true,
    materials: ["Stainless Steel", "Plastic"],
    name: "Blender",
    price: 69.99,
  },
  {
    id: 3,
    discount: 10,
    available: true,
    materials: ["Wood", "Metal", "Plastic"],
    name: "Dining Table",
    price: 299.99,
  },
  {
    id: 4,
    discount: 20,
    available: false,
    materials: ["Leather", "Wood", "Foam"],
    name: "Leather Sofa",
    price: 399.99,
  },
  {
    id: 5,
    discount: 5,
    available: true,
    materials: ["Glass", "Metal"],
    name: "Coffee Table",
    price: 149.99,
  },
  {
    id: 6,
    discount: 15,
    available: true,
    materials: ["Cotton", "Polyester"],
    name: "Bed Sheets",
    price: 29.99,
  },
  {
    id: 7,
    discount: 0,
    available: true,
    materials: ["Ceramic", "Porcelain"],
    name: "Mug Set",
    price: 19.99,
  },
  {
    id: 8,
    discount: 10,
    available: true,
    materials: ["Stainless Steel", "Plastic"],
    name: "Cookware Set",
    price: 129.99,
  },
  {
    id: 9,
    discount: 0,
    available: true,
    materials: ["Metal", "Glass"],
    name: "Wall Clock",
    price: 49.99,
  },
  {
    id: 10,
    discount: 10,
    available: true,
    materials: ["Cotton", "Polyester"],
    name: "Throw Pillow",
    price: 14.99,
  },
];
